"""empty message

Revision ID: ad449a3e5b1a
Revises: f00aa999ff62
Create Date: 2020-09-22 14:30:23.975658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad449a3e5b1a'
down_revision = 'f00aa999ff62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
